server:
  port: 8181 # 项目端口

spring:
  profiles:
    active: dev # 用于区分不同配置环境
  application:
    name: mall-monitor # 项目服务名称
  security:
    user:
      name: liboshuai01
      password: mall@2023
  boot: # 不显示mall-monitor的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}