server:
  port: 8181 # 项目端口

spring:
  security:
    user:
      name: liboshuai01
      password: polaris@2023
  boot: # 不显示Polaris-monitor的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
